//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprijonok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agents()
        {
            this.Agent_release_history = new HashSet<Agent_release_history>();
            this.Orders = new HashSet<Orders>();
            this.Priority_history = new HashSet<Priority_history>();
            this.Product_sale = new HashSet<Product_sale>();
        }
    
        public int agent_ID { get; set; }
        public int agent_type_ID { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string logo { get; set; }
        public string newLogo
        {
            get
            {
                if (logo != null)
                {
                    return logo.Replace("\\agents\\", "Resources/");
                }
                else
                {
                    return null;
                }
            }
        }
        public int priority { get; set; }
        public string director_surname { get; set; }
        public string director_name { get; set; }
        public string director_patronymic { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
    
        public virtual Agent_address Agent_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agent_release_history> Agent_release_history { get; set; }
        public virtual Agents_type Agents_type { get; set; }
        public virtual Minimal_price_history_change Minimal_price_history_change { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Priority_history> Priority_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_sale> Product_sale { get; set; }
    }
}
