//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprijonok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.Products = new HashSet<Products>();
            this.Suppliers = new HashSet<Suppliers>();
        }
    
        public int material_ID { get; set; }
        public string title { get; set; }
        public int material_type_ID { get; set; }
        public int qty_in_package { get; set; }
        public string unit { get; set; }
        public int qty_in_storage { get; set; }
        public int minimal_qty { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public decimal price { get; set; }
    
        public virtual material_type material_type { get; set; }
        public virtual Materials_history Materials_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Suppliers> Suppliers { get; set; }
    }
}
