//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprijonok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials_history
    {
        public int material_ID { get; set; }
        public System.DateTime date { get; set; }
        public int qty { get; set; }
    
        public virtual Materials Materials { get; set; }
    }
}
