//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprijonok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_size
    {
        public int product_ID { get; set; }
        public double width { get; set; }
        public double height { get; set; }
        public double lenght { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
