//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprijonok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_sale
    {
        public int product_sale_ID { get; set; }
        public int product_ID { get; set; }
        public int agent_ID { get; set; }
        public System.DateTime release_date { get; set; }
        public int qty { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual Products Products { get; set; }
    }
}
