//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprijonok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_info
    {
        public int product_ID { get; set; }
        public string description { get; set; }
        public string weight_neto { get; set; }
        public string weight_with_neto { get; set; }
        public string sertificate { get; set; }
        public int standart_type_ID { get; set; }
        public string product_image { get; set; }
        public byte[] time_to_create { get; set; }
        public decimal cost_price { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Standart_types Standart_types { get; set; }
    }
}
